id: A63A08460
title: Short Sang Offering to Kurukullā
type: translation
pechas:
- I69967172
- I98BDB443
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:53.352971
  last_modified_at: 2023-01-04 13:08:53.352981
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I69967172/09C3: '4551'
  I98BDB443/ABDD: '4551'
